
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: bankNetRootPsw

  application:
    name: address-service
server:
  port: 8082